### ISSUE TITLE
#wizards : spell balancing

### ISSUE THREAD

**Issue by gwendalaze** [octothorp-team/sfd#13]
As you may know, some spells are way more used than some other. It may be because they are very situational (in exemple : to the moon, super jump, mind lock). Some other are more "jack of all trade" spells, they can be used in various situation.

Though, some other are used very often, because they are VERY powerful. That's the point of this issue : balancing spells.

I'll start it : 

Shield is too powerful or too easily abusable ; people use it to camp or they spam them to block ways. This can be team work in some case, but this is ridiculous in 1v1 situation, and often lead to draw because of time limit. I got three idea to fix that (only one should be chosen, it would make it under-powered otherwise): 
- reducing to 20 seconds the lifespawn of each blocks of the wall
- increasing its mana cost from 75 to 85 or 90
- reducing teleportation cost from 80 to 50

**Comment by chelog** [comment]
@gwendalaze,
I think it's pretty good solved by **new controls system** as people now can choose spells really easy and counter attack people who just did something as you described
but anyway, if I have to choose, I would choose 1st point: **reduce lifetime**

**Comment by gwendalaze** [comment]
not sure about the fact they can counter attack, but okay, i'm reducing to 20 seconds the lifetime of the blocks.
