### ISSUE TITLE
#Wizards: Gameplay is low-paced now

### ISSUE THREAD

**Issue by chelog** [octothorp-team/sfd#8]
Do you have any suggestions how to make this mode more dynamic?
Now when two players are left, they rarely can kill each other in time limit (90 seconds). That's a problem.  
Previously I changed controls to:  
* [WALK] - change spells
* [WALK] + [BLOCK] - change books

It helped a bit, but we can't use [WALK] button as soon as we want to set it up for spell charging.
Any ideas?

**Comment by GeraldDeschain** [comment]
When there are only 2 players are left, make mana cost and cooldown 2 times smaller?

**Comment by gwendalaze** [comment]
maybe we could find another way to change spellbook
and maybe we could increase mana regen rate

**Comment by chelog** [comment]
@gerald, I find the "some event when two players (or time limit condition) thing", we should re-think it

@gwendalaze, I'll answer in list too :smile: :
* I don't think that changing controls to crouch will help, down is very used button and I think that would be **uncomfortable**, but we may test it a little
* **suggest book-spell** list then, it's necessary to unite them by similar usage
* mana regen increasing seems like a good thing, but **eventually**, like "on time limit condition"
* I didn't really understand what you mean
   * currently players have 50 HP with 1/2 damage, it's like 100HP
   * you suggest to raise damage to 1/1, so actually they will have 50HP, right?
* this really should be an option, like "random appearing of instagib in #Battle", but that's great idea!

**Comment by gwendalaze** [comment]
- Nothing more to say
 - I suggest merging the restoration spell book into  the mysticism one, We could name it "protection" spell book, or something like it. Maybe also something like : 

Energy spellbook : firepucnh , fireball, suicide, fus roh da, to the moon
Summoning spellbook : Crate, paper, anvil, grab, shield
Biomancy spellbook : mind lock, mind control, heal, revive, super jump
 - Nothing more to say
 - Yes, i want there is normal damages with only 50 HP for each players
 - Nothing more to say

**Comment by chelog** [comment]
@gwendalaze, okay, so:
* remove "/2" from Tick_Stats() in damage section
* rearrange spells as you suggested
* test it and tell what you think

**Comment by gwendalaze** [comment]
Well uhh that is all ? Oo You are okay with it ? I mean, don't it waste all your work ?

**Comment by chelog** [comment]
@gwendalaze, that's not a problem for my work since it's in separate branch :D

**Comment by gwendalaze** [comment]
Yeah but i mean if it is the kept solution....

**Comment by chelog** [comment]
@gwendalaze, really that might help a little, but we'll keep this issue open

**Comment by gwendalaze** [comment]
Do the new control system fixed this issue ?

**Comment by chelog** [comment]
@gwendalaze, how do you think?  
I think it totally increased pace of the game

**Comment by gwendalaze** [comment]
@chelog 

I'm not sure the gameplay is fast-paced now, but at least it's not low-paced . The control update dealt well with the pace issue. I think we can not improve the pace that much.
